actinobacteria = {
    "Actinobacteria <actinobacteria>",
    "Actinobacteria",
    "Actinomycetales",
    "Actinomycetaceae",
    "Actinomyces",
    "unclassified Actinomyces",
    "Schaalia",
    "Schaalia suimastitidis",
    "Bifidobacteriales",
    "Bifidobacteriaceae",
    "Bifidobacterium",
    "Bifidobacterium longum",
    "Corynebacteriales",
    "Corynebacteriaceae",
    "Corynebacterium",
    "Corynebacterium mustelae",
    "Corynebacteriales incertae sedis",
    "Lawsonella",
    "Lawsonella clevelandensis",
    "Micrococcales",
    "Micrococcaceae",
    "Kocuria",
    "Propionibacteriales",
    "Propionibacteriaceae",
    "Tessaracoccus",
    "Coriobacteriia",
    "Coriobacteriales",
    "Atopobiaceae",
    "Atopobium",
    "unclassified Atopobium",
    "Atopobium sp. UBA1382",
    "Olsenella",
    "Olsenella uli",
    "unclassified Olsenella",
    "Parolsenella",
    "Parolsenella catena",
    "Coriobacteriaceae",
    "Collinsella",
    "Collinsella aerofaciens",
    "Collinsella ihuae",
    "Collinsella stercoris",
    "unclassified Collinsella",
    "Collinsella sp. UBA1408",
    "Enorma",
    "Enorma timonensis",
    "Eggerthellales",
    "Eggerthellaceae",
    "Cryptobacterium",
    "environmental samples <actinobacteria,genus Cryptobacterium>",
    "Cryptobacterium sp. CAG",
    "Eggerthella",
    "Eggerthella lenta",
    "environmental samples <actinobacteria,genus Eggerthella>",
    "Gordonibacter",
    "Gordonibacter pamelaeae",
    "Raoultibacter",
    "unclassified Raoultibacter",
    "Raoultibacter sp. Marseille-P8396",
    "Slackia",
    "Slackia heliotrinireducens",
    "unclassified Eggerthellaceae",
}

bacteriodetes = {
    "FCB group",
    "Bacteroidetes/Chlorobi group",
    "Bacteroidetes",
    "Bacteroidia",
    "Bacteroidales",
    "Bacteroidaceae",
    "Bacteroides",
    "Bacteroides fragilis",
    "Bacteroides ovatus",
    "Bacteroides stercoris",
    "environmental samples <CFB group bacteria,genus Bacteroides>",
    "uncultured Bacteroides sp.",
    "unclassified Bacteroides",
    "Bacteroides sp. 43_108",
    "Bacteroidales incertae sedis",
    "Phocaeicola",
    "Phocaeicola coprocola",
    "Phocaeicola coprophilus",
    "Phocaeicola plebeius",
    "Phocaeicola vulgatus",
    "Odoribacteraceae",
    "Odoribacter",
    "Prevotellaceae",
    "Prevotella",
    "environmental samples <CFB group bacteria,genus Prevotella>",
    "Prevotella sp. CAG",
    "Prevotella sp. CAG",
    "unclassified Prevotella",
    "Prevotella sp. UBA6339",
    "Prevotella sp. UBA6442",
    "Prevotella sp. UBA6866",
    "Prevotella sp. UBA731",
    "unclassified Prevotellaceae",
    "Rikenellaceae",
    "Alistipes",
    "Alistipes dispar",
    "Tannerellaceae",
    "Parabacteroides",
    "Parabacteroides distasonis",
    "Parabacteroides merdae",
    "unclassified Bacteroidales",
}

firmicutes = {
    "Firmicutes",
    "Bacilli",
    "Bacillales",
    "Bacillaceae",
    "Paenibacillaceae",
    "Paenibacillus",
    "unclassified Bacillales",
    "Lactobacillales",
    "Enterococcaceae",
    "Enterococcus",
    "Enterococcus cecorum",
    "Lactobacillaceae",
    "Lactobacillus",
    "Limosilactobacillus",
    "Streptococcaceae",
    "Streptococcus",
    "Clostridia",
    "Clostridiales",
    "Catabacteriaceae",
    "Catabacter",
    "unclassified Catabacter",
    "Clostridiaceae",
    "Clostridium",
    "Clostridium baratii",
    "Clostridium disporicum",
    "Clostridium perfringens",
    "Clostridium saudiense",
    "environmental samples <firmicutes,genus Clostridium>",
    "Clostridium sp. CAG",
    "Clostridium sp. CAG",
    "Clostridium sp. CAG",
    "Clostridium sp. CAG",
    "uncultured Clostridium sp.",
    "unclassified Clostridium",
    "Clostridium sp. CAG",
    "Hungatella",
    "unclassified Hungatella",
    "Clostridiales incertae sedis",
    "Clostridiales Family XIII. Incertae Sedis",
    "unclassified Clostridiales Family XIII. Incertae Sedis",
    "Clostridiales bacterium UBA643",
    "Intestinimonas",
    "Intestinimonas butyriciproducens",
    "Lawsonibacter",
    "Lawsonibacter asaccharolyticus",
    "Eubacteriaceae",
    "Eubacterium",
    "environmental samples <firmicutes,genus Eubacterium>",
    "uncultured Eubacterium sp.",
    "unclassified Eubacterium",
    "Eubacterium sp. UBA3279",
    "unclassified Eubacteriaceae",
    "Eubacteriaceae bacterium CHKCI004",
    "Hungateiclostridiaceae",
    "Lachnospiraceae",
    "Anaerobutyricum",
    "Anaerobutyricum hallii",
    "Blautia",
    "Blautia argi",
    "Blautia coccoides",
    "Blautia hansenii",
    "Blautia obeum",
    "Blautia wexlerae",
    "environmental samples <firmicutes,genus Blautia>",
    "uncultured Blautia sp.",
    "Dorea",
    "Dorea formicigenerans",
    "Dorea longicatena",
    "environmental samples <firmicutes,genus Dorea>",
    "Dorea sp. CAG",
    "Enterocloster",
    "Enterocloster bolteae",
    "Enterocloster clostridioformis",
    "Fusicatenibacter",
    "Fusicatenibacter saccharivorans",
    "Lachnoclostridium",
    "unclassified Lachnoclostridium",
    "Lacrimispora",
    "Lacrimispora saccharolytica",
    "Marvinbryantia",
    "Marvinbryantia formatexigens",
    "Mediterraneibacter",
    "[Ruminococcus] torques",
    "Mediterraneibacter glycyrrhizinilyticus",
    "Roseburia",
    "environmental samples <firmicutes,genus Roseburia>",
    "uncultured Roseburia sp.",
    "Roseburia hominis",
    "Tyzzerella",
    "Tyzzerella nexilis",
    "unclassified Lachnospiraceae",
    "Lachnospiraceae bacterium",
    "Lachnospiraceae bacterium UBA3332",
    "Lachnospiraceae bacterium UBA7160",
    "Oscillospiraceae",
    "Dysosmobacter",
    "Dysosmobacter welbionis",
    "Oscillibacter",
    "environmental samples <firmicutes,genus Oscillibacter>",
    "Oscillibacter sp. CAG",
    "Peptococcaceae",
    "Peptostreptococcaceae",
    "Clostridioides",
    "Clostridioides difficile",
    "Peptacetobacter",
    "Peptacetobacter hiranonis",
    "Romboutsia",
    "Romboutsia ilealis",
    "Ruminococcaceae",
    "Anaerotruncus",
    "Anaerotruncus colihominis",
    "Faecalibacterium",
    "Faecalibacterium prausnitzii",
    "unclassified Faecalibacterium",
    "Faecalibacterium sp.",
    "Faecalibacterium sp. UBA1360",
    "Faecalibacterium sp. UBA1819",
    "Faecalibacterium sp. UBA7177",
    "Flavonifractor",
    "environmental samples <firmicutes,genus Flavonifractor>",
    "uncultured Flavonifractor sp.",
    "Pseudoflavonifractor",
    "Pseudoflavonifractor capillosus",
    "Ruminococcaceae incertae sedis",
    "[Clostridium] leptum",
    "Ruminococcus",
    "environmental samples <firmicutes,genus Ruminococcus>",
    "uncultured Ruminococcus sp.",
    "unclassified Ruminococcus",
    "unclassified Ruminococcaceae",
    "Ruminococcaceae bacterium UBA1417",
    "unclassified Clostridiales",
    "Clostridiales bacterium",
    "Clostridiales bacterium 1_7_47FAA",
    "Clostridiales bacterium CCNA10",
    "Clostridiales bacterium UBA1390",
    "Clostridiales bacterium VE202-03",
    "unclassified Clostridia",
    "Clostridia bacterium UC5.1-1D4",
    "environmental samples <firmicutes,phylum Firmicutes>",
    "Firmicutes bacterium CAG",
    "Firmicutes bacterium CAG",
    "Firmicutes bacterium CAG",
    "Erysipelotrichia",
    "Erysipelotrichales",
    "Erysipelotrichaceae",
    "Amedibacillus",
    "Amedibacillus dolichus",
    "Catenibacterium",
    "Catenibacterium mitsuokai",
    "Erysipelatoclostridium",
    "[Clostridium] spiroforme",
    "Erysipelatoclostridium ramosum",
    "Faecalicoccus",
    "Faecalicoccus pleomorphus",
    "Holdemanella",
    "Holdemanella biformis",
    "Solobacterium",
    "Solobacterium moorei",
    "unclassified Solobacterium",
    "Turicibacter",
    "unclassified Turicibacter",
    "Turicibacter sp. H121",
    "unclassified Erysipelotrichaceae",
    "Negativicutes",
    "Acidaminococcales",
    "Acidaminococcaceae",
    "Acidaminococcus",
    "Phascolarctobacterium",
    "Selenomonadales",
    "Selenomonadaceae",
    "Megamonas",
    "Megamonas hypermegale",
    "Veillonellales",
    "Veillonellaceae",
    "Dialister",
    "Megasphaera",
    "Tissierellia",
    "Tissierellales",
    "Peptoniphilaceae",
    "unclassified Firmicutes sensu stricto",
}

fusobacteria = {"Fusobacteria", "Fusobacteriia", "Fusobacteriales", "Fusobacteriaceae", "Fusobacterium"}


proteobacteria = {
    "Proteobacteria",
    "Alphaproteobacteria",
    "Betaproteobacteria",
    "Burkholderiales",
    "Burkholderiaceae",
    "Sutterellaceae",
    "Sutterella",
    "Sutterella faecalis",
    "Sutterella megalosphaeroides",
    "unclassified Sutterella",
    "Sutterella sp.",
    "delta/epsilon subdivisions",
    "Deltaproteobacteria",
    "Desulfovibrionales",
    "Desulfovibrionaceae",
    "Desulfovibrio",
    "Desulfovibrio piger",
    "Epsilonproteobacteria",
    "Campylobacterales",
    "Campylobacteraceae",
    "Campylobacter",
    "Campylobacter helveticus",
    "Helicobacteraceae",
    "Helicobacter",
    "Gammaproteobacteria",
    "Aeromonadales",
    "Succinivibrionaceae",
    "Anaerobiospirillum",
    "Anaerobiospirillum succiniciproducens",
    "Succinatimonas",
    "Enterobacterales",
    "Enterobacteriaceae",
    "Escherichia",
    "Escherichia coli",
}


other = {
    "cellular organisms",
    "Bacteria",
    "PVC group",
    "Terrabacteria group",
    "Chloroflexi",
    "Archaea",
    "Euryarchaeota",
}
